### ISSUE TITLE
More detailed description in how to get it self-hosted up and running

### ISSUE THREAD

**Issue by MatthK** [thepersonalaicompany/amurex#4]
I just saw your post on Reddit and would love to try this meeting copilot myself. So I tried to get it up and running, but seem to struggle with a number of steps. Here's what I tried so far.

1. Cloned the repository to my server
2. Ran the `docker build -t amurex-backend .` to create the image
3. Tried to fire up the container, however the command provided didn't work. I needed at least to add the image as well

```
docker run -d --name amurex-backend \
  --restart unless-stopped \
  amurex-backend:latest
```
  This started the container, however it keeps restarting as most likely the .env file is missing.
  When I try to add a -v local/path:/ to the docker start command, it errors out with an `invalid mount config`. I was hoping I could add the .env file there so the container can use those details. So the main question is, where to put the .env file with a docker setup?

Also regarding the .env file.

- OpenAI API Key: I do have https://github.com/open-webui/open-webui already running on my system. This should be OpenAI compatible, and I did create an API key. However, where in the env file would I provide the OpenAI URL to point it to my server?
- Groq API: It looks that part can't be self-hosted? And I somehow get a blocked page when I want to create an API Key there. Need to figure out why I'm getting blocked
- Redis: Is the username/password required for the Redis server, or would it work just with the URL when the server is open?
- Is the Perplexity API Key also required? 

Ideally I would like to self-host all components but it seems with Groq and Perplexity that might not be possible? Are these two needed?

Edit: Two more question I forgot to ask.

- How to point the Chrome extension to my self hosted backend?
- Which port would the self-hosted docker container using?

**Comment by MatthK** [comment]
I also received an error that the REDIS_PORT was missing. Adding it to the URL seemed not to work, so I created a new line `REDIS_PORT=6379` and built the docker image again. Now the backend runs and no errors or other entries showing up in the log.
I guess there are still a few things missing, and I still don't know how to point the Chrome extension to the backend.

**Comment by sansyrox** [comment]
Thanks for raising this @MatthK 😄 

We will fix it asap

**Comment by sansyrox** [comment]
https://github.com/thepersonalaicompany/amurex-backend/issues/8 

moved the remaining here
